package com;

import com.solutions.Solutions;
import org.junit.Assert;
import org.junit.Test;

import java.util.Arrays;


public class Tests {

    @Test
    public void testNonAutoGeneratedResult() {
        int[] A = {1, 5, 47, 51};
        int K = 3;

        int[] solution = Solutions.solution(A, K);

        Assert.assertArrayEquals(new int[] {5, 51}, solution);
    }

    @Test
    public void testAutogeneratedResult() {
        int[] A = {1, 5, 47, 51};
        int K = 3;

        int[] expectedResult = Solutions.solutionNaive(A, K);
        //debug
        System.out.println("expectedResult = " + Arrays.toString(expectedResult));
        int[] solution = Solutions.solution(A, K);

        Assert.assertArrayEquals(expectedResult, solution);
    }
}
